default: &default
  adapter: postgresql

development:
  <<: *default
  database: vindi_development

test:
  <<: *default
  database: vindi_test

production:
  <<: *default
  database: vindi_production
